LESSONS.push({
  id: "lapidando-a-ideia", fase: 1, num: 2,
  title: "Lapidando a Ideia Brilhante",
  tagline: "Descubra como formular perguntas de pesquisa claras e impactantes para transformar sua investigação.",
  quote: { text: "Saber o que perguntar é metade da resposta.", author: "Sócrates" },
  why: "<p>Você já teve uma ideia de pesquisa, mas travou na hora de transformá-la em uma pergunta clara e objetiva? Este módulo é para você. Aqui, você vai aprender como estruturar perguntas científicas relevantes usando a <strong>estratégia PICO</strong> e uma ferramenta com inteligência artificial, um ChatGPT personalizado. Com passos práticos, exemplos médicos e dicas para evitar erros comuns, mostramos como <strong>uma boa pergunta é o alicerce de toda pesquisa de qualidade</strong>.</p>",
  cenario: "<p>Ana Vitória, estudante de segundo ano de Medicina, ingressou em um grupo de pesquisa sobre doenças cardiovasculares. Ao iniciar sua participação, foi questionada: <strong>“Qual será a sua pergunta de pesquisa?”</strong>. Em silêncio, percebeu que não sabia por onde começar. Tinha interesse no tema, acesso à literatura e apoio do orientador, mas faltava a centelha inicial: uma pergunta bem formulada. Essa situação é comum — a formulação da pergunta é o ponto de partida da jornada científica e, muitas vezes, o maior desafio para quem está começando.</p>",
  sections: [
    { icon: "🔍", title: "O que é a pergunta de pesquisa?", html: "<p>A pergunta de pesquisa é uma formulação <strong>clara, objetiva e delimitada</strong> de um problema científico que se deseja investigar. Ela deve ser respondível por meio de métodos científicos, orientando o tipo de estudo, a coleta de dados e a análise estatística.</p><p>Na área da saúde, perguntas bem estruturadas ajudam a responder questões como: <em>“Qual é o impacto da telemedicina no controle da hipertensão arterial em idosos?”</em> ou <em>“A vitamina D reduz a incidência de infecções respiratórias em crianças?”</em>.</p><p>Um dos métodos mais usados para formulá-las é a <strong>estratégia PICO</strong>:</p><ul><li><strong>P</strong> — Paciente ou problema</li><li><strong>I</strong> — Intervenção</li><li><strong>C</strong> — Comparativo</li><li><strong>O</strong> — Outcome / Desfecho / Efeito</li></ul><p>Exemplo: <em>“Qual a diferença de frequência de AVC isquêmico (O) em pacientes com fibrilação atrial (P) tratados com anticoagulantes diretos (I) comparado com varfarina (C)?”</em></p><p>Use um <a href='https://bit.ly/ib-virtual' target='_blank' rel='noopener'>ChatGPT personalizado</a> para transformar um tema amplo em uma pergunta estruturada usando PICO — e colocar tudo isso em prática em alguns segundos.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>Uma boa pergunta de pesquisa <strong>evita desperdício de tempo, recursos e energia</strong>. Perguntas vagas levam a estudos confusos e conclusões frágeis. Em contrapartida, uma pergunta bem definida:</p><ul><li>Facilita a busca bibliográfica;</li><li>Orienta o desenho metodológico;</li><li>Garante relevância clínica e científica.</li></ul><p>A inteligência artificial pode ajudar a testar diferentes formulações, revisar a coerência lógica e sugerir ajustes com base em resultados de pesquisas recentes.</p>" }
  ],
  steps: [
    "<strong>Escolha um tema</strong> de interesse clínico ou pessoal, sem consultar nada.",
    "<strong>Use o modelo PICO</strong> para estruturar a pergunta com auxílio do <a href='https://bit.ly/ib-virtual' target='_blank' rel='noopener'>ChatGPT personalizado</a>.",
    "<strong>Valide a relevância clínica</strong> com os seus conhecimentos no momento.",
    "<strong>Verifique se é viável</strong> responder com os recursos disponíveis.",
    "<strong>Prepare-se para o próximo passo:</strong> ampliar a ideia brilhante (pergunta, hipótese, objetivo e título) para um plano de intenção (resumo estruturado do projeto de pesquisa)."
  ],
  errors: [
    { e: "Tema muito amplo.", s: "Use o <a href='https://bit.ly/ib-virtual' target='_blank' rel='noopener'>ChatGPT personalizado</a> para delimitar e transformar em pergunta PICO." },
    { e: "Usar Consensus ou Semantic Scholar para verificar a originalidade agora.", s: "Neste momento não consultamos nenhuma fonte — precisamos primeiro determinar a nossa pergunta de pesquisa. Essas consultas serão feitas mais adiante." },
    { e: "Demorar mais de 10 minutos para elaborar a pergunta de pesquisa.", s: "Use o ChatGPT personalizado para fazer isso rapidamente." },
    { e: "Demorar mais de um minuto após elaborar a pergunta.", s: "Siga imediatamente para o próximo módulo — aqui é ponto de passagem, não de parada." },
    { e: "Iniciar pela redação do projeto de pesquisa.", s: "Construa o projeto por partes: ideia brilhante → plano de intenção → projeto, avaliando viabilidade e relevância a cada momento. Assim você otimiza tempo e recursos." }
  ],
  licao: "<p>Aprender a perguntar é um ato de <strong>humildade e curiosidade</strong>. A formação na área da saúde exige não apenas repetição de conhecimentos, mas a capacidade de identificar problemas reais e propor caminhos científicos. Mesmo com IA, a essência da boa pesquisa continua sendo humana: <strong>observar, duvidar, questionar</strong>.</p>",
  checklist: [
    "Escolhi um tema de interesse na minha área",
    "Estruturei minha pergunta usando o modelo PICO com o ChatGPT personalizado",
    "Tenho a hipótese, o objetivo e o título gerados com auxílio da IA",
    "Verifiquei a relevância e a originalidade da pergunta com o Consensus",
    "Discuti a viabilidade com meu orientador"
  ],
  dica: "<p>Explore variações da sua pergunta de pesquisa no <a href='https://bit.ly/ib-virtual' target='_blank' rel='noopener'>ChatGPT personalizado</a> — isso dará uma ideia geral das possibilidades. Aqui não é um ponto de parada na jornada, é um <strong>ponto de passagem</strong>: quanto mais rápido conseguir fazer, utilizando a IA como auxílio, melhor.</p><p><strong>Ferramenta — Perplexity:</strong> copie e cole a sua pergunta de pesquisa nesta ferramenta, como degustação. Com o seu tema, use também o ChatGPT na opção <em>Investigar</em> e, no Gemini, a <em>Deep Research</em>.</p><p>Há também um capítulo de livro que aborda a formulação da ideia brilhante com outro ponto de vista: <a href='https://bit.ly/05ideia' target='_blank' rel='noopener'>bit.ly/05ideia</a>.</p>",
  cta: "<p>Agora que você compreendeu a importância e a técnica de elaborar uma boa pergunta de pesquisa, é hora de continuar a jornada. <strong>A boa ciência começa com uma boa pergunta, e ela está em suas mãos.</strong></p><p>A próxima etapa é transformar sua pergunta em um plano de intenção (um resumo estruturado do seu projeto de pesquisa), que dará forma e direção ao seu estudo. No próximo módulo, vamos mostrar como construir esse plano com clareza metodológica, rigor ético e apoio das melhores ferramentas digitais. Tudo isso em alguns minutos. <strong>Avance com propósito!</strong></p>",
  fl: 5, flLabel: "Capítulo 5 — Desenvolver a Ideia Brilhante",
  quiz: [
    { q: "O que significa a sigla PICO na formulação de perguntas de pesquisa?", opts: ["Problema, Investigação, Conclusão, Objetivo", "Paciente/problema, Intervenção, Comparativo, Outcome (desfecho)", "Pesquisa, Ideia, Coleta, Organização", "População, Índice, Causa, Observação"], a: 1, fb: "PICO estrutura a pergunta em: Paciente ou problema, Intervenção, Comparativo e Outcome (desfecho/efeito)." },
    { q: "Por que NÃO se deve usar Consensus ou Semantic Scholar nesta etapa?", opts: ["Porque são ferramentas pagas", "Porque primeiro precisamos determinar a pergunta de pesquisa; as consultas virão depois", "Porque não são confiáveis", "Porque o orientador deve fazer isso"], a: 1, fb: "Neste momento não se consulta nenhuma fonte: o objetivo é determinar a pergunta. A verificação de originalidade virá mais adiante na jornada." },
    { q: "Qual é a consequência típica de uma pergunta de pesquisa vaga?", opts: ["Estudos confusos e conclusões frágeis", "Aprovação mais rápida no Comitê de Ética", "Maior originalidade do estudo", "Redução do tamanho da amostra"], a: 0, fb: "Perguntas vagas levam a estudos confusos e conclusões frágeis; perguntas bem definidas facilitam a busca bibliográfica, orientam o método e garantem relevância." },
    { q: "Quanto tempo, no máximo, o módulo recomenda para elaborar a pergunta de pesquisa?", opts: ["Uma semana, com revisão de literatura", "Um mês, com reuniões do grupo", "Cerca de 10 minutos, com auxílio do ChatGPT personalizado", "Não há limite: quanto mais tempo, melhor"], a: 2, fb: "Demorar mais de 10 minutos é um dos erros comuns — a IA permite estruturar a pergunta rapidamente, pois este é um ponto de passagem, não de parada." }
  ]
});
