LESSONS.push({
  id: "escrevendo-um-resumo", fase: 1, num: 3,
  title: "Escrevendo um Resumo: o Plano de Intenção",
  tagline: "Descubra como escrever um plano de intenção que revela a essência e os desafios da sua pesquisa.",
  quote: { text: "O pensamento ganha forma quando encontra palavras bem escolhidas. Escrever é organizar o futuro do nosso fazer científico.", author: "A Jornada do Pesquisador" },
  why: "<p>Você já teve uma grande ideia para uma pesquisa, mas travou na hora de colocá-la no papel? Escrever um plano de intenção (resumo estruturado do projeto de pesquisa) não é apenas cumprir uma formalidade: é quando o estudante transforma suas ideias em um resumo estruturado e começa a enxergar, de fato, <strong>tudo o que será necessário para realizar a pesquisa</strong>, do domínio do tema às habilidades práticas e atitudes éticas. Este módulo ensina, passo a passo, como elaborar esse plano com clareza e profundidade, usando a inteligência artificial como aliada e preparando você para dialogar com um orientador de forma assertiva e confiante.</p>",
  cenario: "<p>Ana Vitória, estudante de Medicina, havia encontrado um tema que a fascinava: intervenções para dor lombar crônica. Após semanas de leitura, decidiu que estava pronta para escrever seu projeto. No entanto, ao tentar redigir o plano de intenção, sentiu-se paralisada. Como organizar tantas ideias? Quais etapas viriam primeiro? O que exatamente precisava saber, fazer e refletir? Foi nesse processo de escrita que ela percebeu: <strong>redigir um bom plano de intenção não era uma tarefa burocrática, mas uma etapa fundamental</strong> para entender a complexidade de ser pesquisadora.</p>",
  sections: [
    { icon: "🔍", title: "O que é o plano de intenção?", html: "<p>O plano de intenção é um <strong>documento preliminar</strong> que apresenta, de forma organizada e reflexiva, a proposta de um projeto de pesquisa. Diferente de um simples resumo, ele convida o estudante a estruturar suas ideias e a reconhecer os conhecimentos, habilidades e atitudes que serão exigidos ao longo da investigação. Ele é um <strong>resumo estruturado do projeto de pesquisa</strong>.</p><p>Um bom plano de intenção inclui <strong>15 parágrafos</strong>:</p><ol><li>Título</li><li>Autor</li><li>Instituição</li><li>Arquivo</li><li>Contexto</li><li>Objetivo</li><li>Tipo de estudo</li><li>Local</li><li>Amostra</li><li>Procedimentos</li><li>Variáveis</li><li>Método estatístico</li><li>Descritores</li><li>Fontes de fomento</li><li>Conflitos de interesse</li></ol><p>Essa escrita permite visualizar a jornada e antecipar desafios. Você pode usar o <a href='https://bit.ly/pi-geral' target='_blank' rel='noopener'>ChatGPT personalizado</a> para gerar rascunhos, testar versões do texto e organizar as ideias.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>Escrever um plano de intenção bem estruturado é como <strong>desenhar o mapa da sua pesquisa</strong>. Ao colocar suas ideias no papel, você se depara com questões fundamentais: é um tema relevante? Tenho acesso aos dados? Preciso de quais competências para conduzir esse estudo?</p><p>Esse processo revela a complexidade envolvida: do raciocínio científico à gestão de tempo, da comunicação com o orientador ao conhecimento de normas éticas e à escrita acadêmica. Com apoio da IA, é possível:</p><ul><li>Simular diferentes modelos de plano;</li><li>Avaliar se os objetivos estão coerentes;</li><li>Verificar se a metodologia é exequível;</li><li>Criar checklists de competências a desenvolver.</li></ul>" }
  ],
  steps: [
    "<strong>Escreva o seu plano de intenção</strong> com auxílio de uma inteligência artificial personalizada, usando a ideia brilhante como ponto de partida: <a href='https://bit.ly/pi-geral' target='_blank' rel='noopener'>bit.ly/pi-geral</a>.",
    "<strong>Verifique a relevância</strong> com base em dados da literatura: <a href='https://www.perplexity.ai' target='_blank' rel='noopener'>Perplexity</a>, <a href='https://consensus.app' target='_blank' rel='noopener'>Consensus</a> e <a href='https://www.semanticscholar.org' target='_blank' rel='noopener'>Semantic Scholar</a>.",
    "<strong>Apresente para um possível orientador</strong> e solicite feedback, é obrigatório encontrar um orientador nessa hora.",
    "<strong>Valide a relevância clínica</strong> com seu orientador.",
    "<strong>Realize uma autorreflexão</strong> respondendo a duas perguntas: a pesquisa é relevante? A pesquisa é viável?"
  ],
  errors: [
    { e: "Tratar o plano de intenção como uma formalidade.", s: "Encare o plano como uma ferramenta diagnóstica da sua prontidão para pesquisar." },
    { e: "Ignorar a necessidade de habilidades específicas.", s: "Use a IA para criar listas de competências e planeje o seu desenvolvimento." }
  ],
  licao: "<p>Escrever o plano de intenção é um convite ao <strong>autoconhecimento acadêmico</strong>. Ao tentar explicar sua ideia, você revela a si mesmo o quanto já compreende do tema, o que ainda precisa aprender e quais atitudes serão fundamentais. É um primeiro ensaio da autonomia intelectual, com o apoio da inteligência artificial, mas guiado pela consciência do pesquisador.</p>",
  checklist: [
    "Escrevi o plano de intenção com o ChatGPT personalizado",
    "Avaliei a relevância da pesquisa",
    "Avaliei a viabilidade da pesquisa",
    "Solicitei validação de um orientador ou mentor"
  ],
  dica: "<p><strong>Ferramenta, Consensus.app:</strong> copie e cole a sua pergunta de pesquisa nesta ferramenta, como degustação, para verificar se a pergunta já foi amplamente respondida ou se há lacunas a explorar.</p><p>Use o <a href='https://scite.ai' target='_blank' rel='noopener'>Scite.ai</a> para encontrar artigos e ver como foram citados em outros trabalhos, isso ajuda a construir um plano mais fundamentado. Ferramentas como o ExplainPaper ajudam a compreender artigos técnicos que embasarão seu projeto.</p><p>Há também um capítulo de livro que aborda o tema com outro ponto de vista: <a href='https://bit.ly/06plano' target='_blank' rel='noopener'>bit.ly/06plano</a>.</p>",
  cta: "<p>Agora que você compreendeu a importância de escrever o plano de intenção, é hora de <strong>validar externamente</strong>. O plano de intenção é o seu ensaio inaugural como pesquisador. Ao terminar, não terá apenas um documento estruturado, terá uma visão mais madura e estratégica da sua proposta científica.</p><p>Com esse mapa em mãos, você estará pronto para o próximo passo essencial da jornada: a <strong>revisão da literatura</strong>. No próximo módulo, vamos explorar como mergulhar criticamente no conhecimento existente, identificar lacunas e posicionar sua pesquisa com consistência teórica e atualidade científica. Avance com confiança, o conhecimento já o espera.</p>",
  fl: 6, flLabel: "Capítulo 6, Redigir o Plano de Intenção",
  quiz: [
    { q: "O que é o plano de intenção?", opts: ["O projeto de pesquisa completo, pronto para o Comitê de Ética", "Um resumo estruturado do projeto de pesquisa, com 15 parágrafos", "Uma carta de apresentação para o orientador", "A lista de referências bibliográficas do estudo"], a: 1, fb: "É um documento preliminar e reflexivo, um resumo estruturado do projeto, que vai do título aos conflitos de interesse em 15 parágrafos." },
    { q: "Qual é o principal erro ao lidar com o plano de intenção?", opts: ["Escrevê-lo antes do projeto completo", "Usar inteligência artificial para o rascunho", "Tratá-lo como mera formalidade", "Mostrá-lo ao orientador cedo demais"], a: 2, fb: "O plano deve ser encarado como uma ferramenta diagnóstica da sua prontidão para pesquisar, não como burocracia." },
    { q: "Neste momento da jornada, o que se torna obrigatório?", opts: ["Submeter ao Comitê de Ética", "Encontrar um orientador e solicitar feedback", "Publicar o resumo em um congresso", "Coletar os primeiros dados"], a: 1, fb: "O passo a passo é claro: apresente o plano a um possível orientador, é obrigatório encontrar um orientador nessa hora." },
    { q: "Quais são as duas perguntas da autorreflexão ao final do plano de intenção?", opts: ["A pesquisa é cara? A pesquisa é rápida?", "A pesquisa é relevante? A pesquisa é viável?", "A pesquisa é original? A pesquisa é publicável?", "A pesquisa é ética? A pesquisa é estatística?"], a: 1, fb: "Relevância e viabilidade são os dois critérios que acompanham toda a jornada, avaliados a cada nova etapa antes de escrever o projeto completo." }
  ]
});
