LESSONS.push({
  id: "testando-antes-de-errar", fase: 1, num: 5,
  title: "Testando Antes de Errar",
  tagline: "Verifique se sua pesquisa é exequível na prática antes de escrever o projeto final.",
  quote: { text: "É na prática que a teoria encontra sua verdade, ou revela sua ilusão.", author: "Adaptado de Friedrich Engels" },
  why: "<p>Você já estruturou sua pergunta de pesquisa, fez a revisão da literatura e tem um plano de intenção em mãos. Mas <strong>será que sua pesquisa funciona na prática?</strong> Este módulo é o teste decisivo. Aqui, você vai aprender a verificar se tem os instrumentos certos, se os procedimentos são viáveis e se você (ou sua equipe) está realmente pronto para executar o estudo com segurança e rigor. Você vai garantir que sua pesquisa é mais que uma boa ideia: <strong>é uma proposta possível</strong>.</p>",
  cenario: "<p>Ana Vitória, aluna do 3º ano de Medicina, revisou a literatura, aprimorou sua pergunta de pesquisa e estava pronta para escrever o projeto. No entanto, ao simular a aplicação do questionário com colegas, percebeu falhas na clareza das perguntas e dificuldades técnicas na plataforma de coleta. Foi então que seu orientador sugeriu: <strong>“Antes de escrever o projeto, teste tudo. A teoria só se transforma em ciência quando funciona na prática.”</strong></p>",
  sections: [
    { icon: "🔍", title: "O que é?", html: "<p>Esta etapa, chamada <strong>testes de instrumentos e de procedimentos</strong>, é um momento de validação prática. Aqui, o pesquisador verifica se dispõe dos recursos técnicos e humanos para aplicar seu plano de intenção com precisão. Exemplos:</p><ul><li>Se a coleta envolve exames de imagem: o equipamento está disponível? O pesquisador sabe utilizá-lo?</li><li>Se envolve entrevistas: o roteiro é compreensível para os participantes?</li></ul><p>💡 Você pode usar o ChatGPT para simular entrevistas, revisar instruções de instrumentos e criar listas de verificação para procedimentos. Para mais detalhes, veja o <a href='https://aldemararaujo.github.io/ebook' target='_blank' rel='noopener'>ebook dedicado ao teste de instrumentos e procedimentos</a>.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>Testar os instrumentos e procedimentos é a <strong>ponte entre o planejamento teórico e a execução prática</strong>. É quando o pesquisador verifica se o que foi idealizado no papel pode realmente ser realizado no mundo real, com os recursos, habilidades e tempo disponíveis. Ignorar essa etapa pode gerar consequências sérias:</p><ul><li><strong>Dados inválidos ou inconsistentes</strong>, se os instrumentos não estiverem calibrados ou forem aplicados de maneira inadequada;</li><li><strong>Desperdício de tempo e recursos</strong>, com coletas que precisam ser refeitas ou descartadas;</li><li><strong>Riscos éticos</strong>, especialmente em estudos com seres humanos;</li><li><strong>Frustrações e atrasos</strong>, que muitas vezes levam ao abandono da pesquisa.</li></ul><p>Em projetos da área da saúde, essa etapa é ainda mais crítica: envolve pacientes, equipamentos clínicos, prontuários e ambientes hospitalares. A verificação prática permite <strong>antecipar dificuldades técnicas, ajustar procedimentos e reavaliar a exequibilidade</strong> de todo o plano.</p><p>📌 Um formulário de entrevista pode parecer ótimo no plano de intenção, mas confuso quando aplicado. Um simples teste com um colega ou paciente simulado pode revelar a necessidade de ajustes cruciais.</p><p><strong>Como a IA pode ajudar:</strong> o ChatGPT pode simular entrevistas, criar fluxogramas, gerar checklists adaptados à sua metodologia e revisar instruções técnicas. Consensus e Perplexity ajudam a validar se os métodos escolhidos são coerentes com estudos semelhantes.</p>" }
  ],
  steps: [
    "<strong>Revise o plano de intenção:</strong> percorra cada um dos 15 itens e identifique todos os instrumentos (formulários, equipamentos, escalas, softwares) e procedimentos (entrevista, exame físico, coleta de amostras) planejados.",
    "<strong>Faça anotações específicas:</strong> ao final de cada item do plano, detalhe quais instrumentos serão utilizados, como será feito o procedimento e quem será responsável por cada parte.",
    "<strong>Classifique as tarefas:</strong> um asterisco (*) para o que você pode realizar sozinho; dois asteriscos (**) para o que exige apoio técnico, treinamento ou contratação. Ex.: preencher formulário online (*), realizar ultrassonografia transvaginal (**).",
    "<strong>Priorize o que precisa ser resolvido:</strong> numere os itens por urgência, equipamentos caros ou escassos, procedimentos que dependem de aprovação institucional, barreiras éticas ou logísticas.",
    "<strong>Execute os testes:</strong> aplique o formulário em um colega ou voluntário simulado, use o equipamento em ambiente controlado, verifique se os dados são armazenados corretamente e cronometre o tempo de cada etapa.",
    "<strong>Elabore um plano de ação:</strong> para cada falha ou incerteza, defina o que precisa ser resolvido, quem poderá ajudar e quanto tempo e custo estão envolvidos.",
    "<strong>Prepare os quatro documentos obrigatórios:</strong> formulário de coleta de dados (Google Forms), tabela de dados individuais (Google Sheets), Termo de Consentimento Livre e Esclarecido (TCLE, no modelo do CEP) e Termo de Autorização da Realização da Pesquisa.",
    "<strong>Valide com o orientador:</strong> compartilhe os registros dos testes, os ajustes realizados e a versão final dos documentos. Essa validação é obrigatória e protege contra falhas previsíveis."
  ],
  errors: [
    { e: "Pressa em redigir o projeto sem testar os instrumentos e os procedimentos.", s: "Adie a redação até validar a exequibilidade prática." },
    { e: "Achar que a revisão da literatura basta.", s: "Complemente com simulações práticas." },
    { e: "Falta de documentação dos testes realizados.", s: "Crie registros claros para cada etapa com ajuda de planilhas ou IA." }
  ],
  licao: "<p>A pesquisa científica só avança quando <strong>teoria e prática caminham juntas</strong>. Testar os instrumentos e procedimentos é um ato de responsabilidade, humildade e compromisso com a qualidade científica. A IA pode ser aliada, mas é a consciência crítica do pesquisador que transforma testes em confiança.</p>",
  checklist: [
    "Listei todos os instrumentos e procedimentos necessários",
    "Realizei testes de funcionamento",
    "Classifiquei as tarefas por autonomia (*) ou necessidade de apoio (**)",
    "Criei o formulário de coleta de dados",
    "Criei a tabela individual de dados",
    "Elaborei o TCLE com base nas orientações do CEP",
    "Tenho o Termo de Autorização para a Realização da Pesquisa",
    "Validei todos os recursos com o orientador"
  ],
  dica: "<p>📎 Acesse gratuitamente o conteúdo completo sobre esta etapa em <a href='https://bit.ly/08tip' target='_blank' rel='noopener'>bit.ly/08tip</a>.</p><p>✅ <strong>Leitura obrigatória:</strong> <a href='https://aldemararaujo.github.io/ebook' target='_blank' rel='noopener'>aldemararaujo.github.io/ebook</a>, um ebook dedicado apenas ao teste de instrumentos e de procedimentos.</p><p>Use a plataforma MyNCBI para ativar alertas sobre métodos semelhantes ao seu.</p>",
  cta: "<p>Você chegou até aqui com clareza teórica e curiosidade investigativa. Agora está diante de um ponto decisivo: <strong>validar se aquilo que você deseja fazer é realmente algo que pode ser feito</strong>. É o momento de sair da zona de ideias e entrar no território da ação, identificar limites, corrigir falhas e fortalecer sua proposta antes de submetê-la à crítica acadêmica.</p><p>🔍 Não subestime essa etapa: muitos projetos falham não por falta de boas ideias, mas por ausência de preparo prático. Ser cientista também é ser estrategista. Pegue seu plano de intenção, simule seus procedimentos, questione seus instrumentos e coloque à prova tudo o que escreveu. <strong>Avance apenas quando estiver seguro de que sua pesquisa é viável tanto na teoria quanto na prática</strong>, aí você estará pronto para escrever o projeto de pesquisa completo.</p>",
  fl: 8, flLabel: "Capítulo 8, Testar os Instrumentos e os Procedimentos",
  quiz: [
    { q: "Qual é o objetivo central da etapa de testes de instrumentos e procedimentos?", opts: ["Coletar os primeiros dados oficiais da pesquisa", "Validar na prática se o plano pode ser executado com os recursos, habilidades e tempo disponíveis", "Substituir a revisão da literatura", "Treinar o orientador nos equipamentos"], a: 1, fb: "É o ensaio geral do projeto: verificar se tudo o que foi planejado pode ser realizado no mundo real antes de redigir o projeto final." },
    { q: "No sistema de classificação de tarefas, o que significam os dois asteriscos (**)?", opts: ["Tarefa já concluída", "Tarefa que o pesquisador realiza sozinho", "Tarefa que exige apoio técnico, treinamento ou contratação", "Tarefa opcional"], a: 2, fb: "Um asterisco (*): você faz sozinho. Dois asteriscos (**): precisa de auxílio técnico, como realizar uma ultrassonografia transvaginal." },
    { q: "Quais são os quatro documentos essenciais a preparar nesta etapa?", opts: ["Projeto, artigo, pôster e relatório", "Formulário de coleta, tabela de dados individuais, TCLE e Termo de Autorização do Local da Pesquisa", "Currículo, diploma, carta e orçamento", "Resumo, abstract, índice e referências"], a: 1, fb: "Formulário de coleta de dados (Google Forms), tabela de dados individuais (Google Sheets), TCLE e Termo de Autorização da Realização da Pesquisa." },
    { q: "Qual das consequências abaixo decorre de ignorar os testes práticos?", opts: ["Aprovação mais rápida no CEP", "Dados inválidos, desperdício de recursos, riscos éticos e abandono da pesquisa", "Aumento automático da amostra", "Melhora na escrita do projeto"], a: 1, fb: "Sem testes, os instrumentos podem falhar na aplicação real, gerando dados inconsistentes, retrabalho, riscos éticos e frustração." }
  ]
});
