LESSONS.push({
  id: "projeto-de-pesquisa", fase: 1, num: 6,
  title: "O Projeto de Pesquisa: o Mapa da Execução",
  tagline: "Juntando as partes até agora para ter um projeto viável, claro e aprovado, com apoio da inteligência artificial.",
  quote: { text: "Um mapa não impede os desvios do caminho, mas permite que eles sejam feitos com consciência e propósito.", author: "A Jornada do Pesquisador" },
  why: "<p>Você já teve uma ideia de pesquisa promissora, mas travou na hora de colocá-la no papel? Este módulo é o seu guia prático para transformar <strong>dúvidas em estrutura, ideias em planejamento e intenções em execução</strong>. Aqui você aprende, passo a passo, a construir um projeto de pesquisa robusto, ético e cientificamente válido, integrando ferramentas de IA como ChatGPT, Consensus e ResearchRabbit. Seja para obter financiamento, aprovação ética ou reconhecimento acadêmico: não basta sonhar com uma boa pesquisa, <strong>é preciso saber planejá-la</strong>. Não é apenas sobre escrever bem, é sobre pensar bem.</p>",
  cenario: "<p>Ana Vitória sentia que finalmente havia encontrado o foco de sua pesquisa: o impacto da música na ansiedade de pacientes pré-cirúrgicos. Depois de testar escalas de ansiedade e planejar o ambiente hospitalar, percebeu que havia chegado ao momento mais exigente da jornada: organizar todas essas partes em um documento sólido e claro. <strong>“Como transformar minhas anotações em um projeto real?”</strong>, questionava-se. Era chegada a hora de redigir o projeto de pesquisa.</p>",
  sections: [
    { icon: "🔍", title: "O que é?", html: "<p>O projeto de pesquisa é um <strong>documento estruturado e argumentativo</strong> que apresenta, de forma clara, precisa e detalhada, os elementos essenciais de um estudo científico: da contextualização do problema à descrição dos procedimentos metodológicos e éticos, passando pela justificativa, objetivos, plano de análise, cronograma e fontes de financiamento.</p><p>Muito mais do que um requisito formal, o projeto funciona como um <strong>contrato intelectual e operacional</strong> entre o pesquisador e os diversos atores envolvidos na ciência: orientadores, comitês de ética, agências de fomento, instituições parceiras e até o leitor futuro. Ele deve demonstrar que a pesquisa é <strong>relevante, exequível, ética e cientificamente fundamentada</strong>.</p><p>💡 Use o ExplainPaper para decifrar textos metodológicos complexos de artigos e adaptar boas práticas ao seu próprio projeto.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>Um projeto de pesquisa bem escrito garante que:</p><ul><li><strong>A pesquisa seja viável e replicável</strong>, qualquer outro pesquisador, seguindo as mesmas etapas, poderá reproduzir os resultados;</li><li><strong>As etapas estejam claramente planejadas e justificadas</strong>, cada decisão metodológica tem um porquê, com fluxo coerente entre objetivos, métodos e análise;</li><li><strong>Os riscos éticos estejam antecipados e mitigados</strong>, privacidade, consentimento informado e possíveis desconfortos previstos desde o início;</li><li><strong>Haja mais chances de aprovação pelo Comitê de Ética</strong>, clareza e estrutura demonstram responsabilidade;</li><li><strong>Agências de fomento reconheçam o valor da proposta</strong>, um bom projeto convence avaliadores de que o estudo é relevante e realizável nos prazos e recursos propostos.</li></ul><p>A IA pode ajudar revisando a coerência dos objetivos, simulando metodologias alternativas, testando hipóteses teóricas, sugerindo ajustes de linguagem e gerando checklists de completude.</p>" },
    { icon: "🧱", title: "A estrutura canônica do projeto", html: "<p>Elementos pré-textuais: folha de rosto do Comitê de Ética, capa e folha de rosto, índice, lista de abreviaturas/siglas/símbolos, resumo e abstract. Em seguida:</p><ol><li><strong>Introdução (justificativa):</strong> contexto, hipótese e objetivo;</li><li><strong>Métodos:</strong> tipo de estudo (e tempo de seguimento, se aplicável); local (descrição geral, específica e CNAE, se aplicável); amostra (critérios de inclusão, critérios de exclusão, amostragem, consentimento livre e esclarecido); procedimentos (intervenções, testes ou exposições); variáveis (primárias, secundárias e dados complementares); método estatístico (cálculo do tamanho da amostra, análise de dados, apresentação dos resultados);</li><li><strong>Etapas da pesquisa e cronograma:</strong> todas as etapas do estudo, com prazos;</li><li><strong>Materiais e orçamento:</strong> recursos necessários e fontes de financiamento;</li><li><strong>Monitoramento da pesquisa:</strong> medidas para minimizar riscos e proteger a confidencialidade;</li><li><strong>Análise de riscos e benefícios</strong> para os participantes;</li><li><strong>Propriedade da informação e divulgação:</strong> como os dados serão tratados e os resultados publicados;</li><li><strong>Documentação complementar:</strong> referências, Termo de Autorização, modelo do TCLE, formulários de coleta, tabela de dados individuais, currículo dos pesquisadores e formulário de conflito de interesses.</li></ol>" }
  ],
  steps: [
    "<strong>Copie um modelo confiável:</strong> use modelos de instituições ou adaptados por orientadores, por exemplo, o modelo disponível em <a href='http://bit.ly/projeto7' target='_blank' rel='noopener'>bit.ly/projeto7</a>.",
    "<strong>Adapte com sua identidade:</strong> evite copiar literalmente. Seu projeto deve refletir sua pergunta, contexto e realidade.",
    "<strong>Siga a estrutura canônica</strong> (detalhada acima), preenchendo cada seção com os insumos das etapas anteriores: ideia brilhante, plano de intenção e testes práticos.",
    "<strong>Use a IA como aliada:</strong> ChatGPT (organiza ideias, rascunha parágrafos, revisa linguagem), Zotero/Mendeley (referências), ResearchRabbit (expande o referencial teórico) e Consensus (evidências para a justificativa).",
    "<strong>Mantenha rotina de escrita orientada:</strong> consulte projetos aprovados, converse com colegas experientes e use Notion ou Google Docs para transformar esboços em argumentos convincentes."
  ],
  errors: [
    { e: "Redigir antes de testar a viabilidade.", s: "Teste todos os procedimentos antes de consolidar no projeto." },
    { e: "Ser genérico nos objetivos e na metodologia.", s: "Use a IA para refinar e detalhar cada item." },
    { e: "Apresentar o tamanho da amostra no item amostragem.", s: "O tamanho da amostra fica no item 'cálculo do tamanho da amostra', dentro do método estatístico." },
    { e: "Ignorar o papel do estatístico.", s: "Inclua um especialista desde o início. A IA também pode simular análises estatísticas." }
  ],
  licao: "<p>Redigir um projeto de pesquisa é mais do que escrever um documento: é <strong>assumir a responsabilidade de transformar uma ideia inicial em um caminho viável, ético e cientificamente relevante</strong>. É o momento em que a dúvida se torna decisão, a intenção ganha forma concreta e a criatividade se submete ao rigor metodológico. Escrever o projeto é também escrever a identidade do pesquisador que estamos nos tornando.</p>",
  checklist: [
    "Testei os instrumentos e procedimentos na prática",
    "Tenho uma pergunta de pesquisa clara",
    "Escrevi objetivos coerentes com a pergunta",
    "Escolhi uma metodologia viável",
    "Consultei um estatístico ou IA para o plano de análise",
    "Redigi todos os itens com clareza e organização",
    "Usei ferramentas de IA para revisar e ampliar",
    "Validei todos os recursos com o orientador"
  ],
  dica: "<p>Explore o <a href='https://scite.ai' target='_blank' rel='noopener'>Scite.ai</a> para verificar se suas referências estão sendo citadas de forma positiva, negativa ou neutra.</p><p>Acesse o capítulo “Redigir o Projeto de Pesquisa” no livro original da série FiatLux: <a href='https://bit.ly/2024fiatlux' target='_blank' rel='noopener'>bit.ly/2024fiatlux</a>, o essencial está no bloco de aprofundamento acima.</p><p>Consulte o Manual de Iniciação Científica da sua instituição, onde geralmente há um modelo pronto para adaptar: <a href='https://bit.ly/7png' target='_blank' rel='noopener'>bit.ly/7png</a>.</p>",
  cta: "<p>Agora que você construiu o projeto, está pronto para submetê-lo ao Comitê de Ética. Mas atenção: <strong>a submissão ética não é um ato automático</strong>. Ela exige compreender profundamente os princípios da bioética, autonomia, beneficência, não maleficência e justiça, e saber aplicá-los ao seu contexto: prever riscos, garantir confidencialidade, respeitar a vontade dos participantes e ter clareza sobre o uso dos dados.</p><p>O sistema de submissão exige documentos complementares (TCLE, carta de autorização, orçamento, cronograma) e o preenchimento correto da Plataforma Brasil, cada erro pode atrasar semanas o início do projeto. No próximo módulo, vamos entender como garantir a aprovação e respeitar os princípios éticos que sustentam a pesquisa em saúde.</p>",
  fl: 9, flLabel: "Capítulo 9, Redigir o Projeto de Pesquisa",
  quiz: [
    { q: "Qual metáfora define o papel do projeto de pesquisa na jornada?", opts: ["Um diário de bordo da coleta", "Um contrato intelectual e operacional entre o pesquisador e os atores da ciência", "Uma carta de intenções informal", "Um resumo ampliado do artigo final"], a: 1, fb: "O projeto formaliza compromissos com orientadores, comitês de ética, agências de fomento e instituições, demonstrando relevância, exequibilidade, ética e fundamentação." },
    { q: "Onde deve aparecer o tamanho da amostra no projeto?", opts: ["No item amostragem", "Na introdução", "No cálculo do tamanho da amostra, dentro do método estatístico", "No cronograma"], a: 2, fb: "Erro comum: apresentar o tamanho da amostra na amostragem. O lugar correto é o cálculo do tamanho da amostra, no método estatístico." },
    { q: "O que a replicabilidade de um projeto bem escrito significa?", opts: ["Que o projeto pode ser copiado por colegas", "Que qualquer pesquisador, seguindo as mesmas etapas, poderá reproduzir os resultados", "Que o estudo será repetido pelo próprio autor", "Que a amostra é grande o suficiente"], a: 1, fb: "A descrição clara e detalhada das etapas permite reprodução por outros pesquisadores, fortalecendo a validade científica do estudo." },
    { q: "Quais princípios da bioética devem guiar a submissão ao Comitê de Ética?", opts: ["Autonomia, beneficência, não maleficência e justiça", "Rapidez, economia, clareza e concisão", "Originalidade, impacto, citação e publicação", "Hipótese, objetivo, método e resultado"], a: 0, fb: "Os quatro princípios clássicos da bioética sustentam a pesquisa com seres humanos e devem ser aplicados ao contexto do seu estudo." }
  ]
});
