LESSONS.push({
  id: "guardia-da-ciencia", fase: 1, num: 7,
  title: "A Guardiã da Ciência: Ética e Submissão ao CEP",
  tagline: "Da intenção à permissão: como submeter seu projeto ao CEP e garantir a aprovação ética.",
  quote: { text: "A ciência só é legítima quando respeita a dignidade humana. Por isso, nenhuma pesquisa com pessoas deve começar sem antes passar pelo crivo ético.", author: "A Jornada do Pesquisador" },
  why: "<p>Você finalizou seu projeto de pesquisa, mas não sabe exatamente o que fazer agora? Este módulo é para você. Aqui, você vai entender por que a aprovação ética <strong>não é burocracia, mas uma garantia</strong> de que sua pesquisa respeita os participantes e a ciência. Você aprenderá quais documentos preparar, como usar a Plataforma Brasil e como a IA pode ajudá-lo a revisar o TCLE e antecipar as pendências mais comuns. Em poucos minutos, você terá um roteiro claro para avançar com confiança.</p>",
  cenario: "<p>Ana Vitória olhava para a tela do computador com uma mistura de alívio e ansiedade. O projeto estava pronto, cada objetivo alinhado, a metodologia revisada, os instrumentos testados. Mas, ao abrir a pasta de documentos, percebeu que faltava algo fundamental: a aprovação do Comitê de Ética em Pesquisa. Sem ela, nenhum paciente poderia ser abordado, nenhum dado coletado. <strong>“O que eu preciso enviar? Como funciona a Plataforma Brasil?”</strong>, questionou-se. Era chegada a hora de passar pela guardiã da ciência.</p>",
  sections: [
    { icon: "🔍", title: "O que é?", html: "<p>A submissão ao Comitê de Ética em Pesquisa (CEP) é o período entre a conclusão da redação do projeto e a obtenção da aprovação ética formal. <strong>Nenhuma coleta de dados pode ser iniciada antes dessa aprovação.</strong> Trata-se de um requisito ético, científico e legal, regulamentado pela Resolução CNS 466/2012 e pelas Boas Práticas Clínicas internacionais.</p><p>O CEP é um <strong>órgão independente</strong> que avalia os aspectos éticos e metodológicos do projeto, assegurando que os participantes estejam protegidos contra qualquer forma de dano, risco ou abuso. Toda a submissão é feita eletronicamente pela <a href='https://plataformabrasil.saude.gov.br' target='_blank' rel='noopener'>Plataforma Brasil</a>, o sistema oficial nacional para pesquisas com seres humanos no Brasil.</p><p>💡 Use o ChatGPT para revisar o seu TCLE antes da submissão: peça que identifique termos técnicos que possam dificultar a compreensão do participante e sugira versões mais acessíveis.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>A aprovação ética é indispensável porque:</p><ul><li><strong>Protege os participantes:</strong> o CEP garante que ninguém seja exposto a riscos desnecessários, inclusive os provenientes de pesquisas mal planejadas. Proteger o sujeito da pesquisa é também protegê-lo de ciência de má qualidade;</li><li><strong>Estabelece corresponsabilidade institucional:</strong> ao aprovar o projeto, o comitê compartilha a responsabilidade pela execução, conferindo legitimidade científica e institucional;</li><li><strong>Garante avaliação ético-científica independente:</strong> avaliadores externos analisam tanto o TCLE, os riscos e benefícios quanto o método, porque uma pesquisa mal planejada também é eticamente inaceitável;</li><li><strong>É um requisito legal:</strong> iniciar a coleta sem aprovação é uma infração ética e pode invalidar toda a pesquisa, inclusive para publicação;</li><li><strong>Fortalece a credibilidade:</strong> um projeto aprovado tem mais chances de ser aceito em eventos e periódicos indexados.</li></ul><p>A IA pode ajudar a revisar documentos, simular as pendências mais comuns e preparar respostas para questionamentos do comitê antes mesmo de recebê-los.</p>" }
  ],
  steps: [
    "<strong>Faça o cadastro na Plataforma Brasil:</strong> acesse <a href='https://plataformabrasil.saude.gov.br' target='_blank' rel='noopener'>plataformabrasil.saude.gov.br</a> e crie seu perfil como pesquisador, vinculando-se à sua instituição. O cadastro exige CPF, é individual e indispensável.",
    "<strong>Prepare os documentos exigidos</strong> em PDF: projeto completo, TCLE, formulários de coleta de dados, cronograma, análise de riscos e benefícios e formulário de conflito de interesses.",
    "<strong>Revise o TCLE com IA:</strong> cole o TCLE no ChatGPT e peça revisão de clareza, adequação ao nível de escolaridade dos participantes e completude das informações obrigatórias pela Resolução 466/2012.",
    "<strong>Inicie a submissão eletrônica:</strong> na Plataforma Brasil, clique em “Nova Submissão”, selecione o tipo de estudo, preencha os formulários e anexe os documentos. Atenção: erros simples geram pendências que atrasam semanas.",
    "<strong>Escolha o CEP responsável:</strong> selecione o comitê vinculado à sua instituição ou ao local da pesquisa. Confirme com seu orientador e verifique se o CEP está ativo.",
    "<strong>Acompanhe o andamento regularmente:</strong> monitore o sistema e responda às pendências com agilidade e clareza. Use IA para redigir as respostas, se necessário, mas sempre revise antes de enviar."
  ],
  errors: [
    { e: "Submeter o projeto com documentos faltando ou incompletos.", s: "Faça uma checklist de documentos antes de enviar. Use o ChatGPT para verificar se o projeto atende à Resolução CNS 466/2012." },
    { e: "Redigir o TCLE com linguagem técnica inacessível.", s: "O TCLE deve ser compreendido por qualquer pessoa. Use IA para simplificar e peça a alguém sem formação na área que confirme o entendimento." },
    { e: "Submeter o projeto antes de estar completamente finalizado.", s: "Só envie após revisar todos os itens. Pendências metodológicas atrasam semanas e demonstram imaturidade científica ao comitê." },
    { e: "Achar que a responsabilidade termina com a aprovação.", s: "Após aprovado, é obrigatório enviar relatórios de acompanhamento a cada seis meses e um relatório final. O compromisso ético dura enquanto a pesquisa durar." },
    { e: "Submeter para o CEP errado.", s: "Confirme com o orientador qual é o CEP vinculado à sua instituição. Enviado ao comitê errado, o processo precisa ser refeito." }
  ],
  licao: "<p>Passar pelo CEP não é um obstáculo: é um <strong>ato de comprometimento com a ciência e com as pessoas</strong> que aceitam participar da sua pesquisa. Todo erro metodológico é também um erro ético, pois desperdiça recursos e expõe participantes a procedimentos sem propósito real. A aprovação ética não é o fim do planejamento: <strong>é a sua coroação</strong>. Pesquisar com rigor e com respeito são inseparáveis.</p>",
  checklist: [
    "Projeto de pesquisa finalizado e revisado",
    "TCLE redigido em linguagem acessível e revisado com IA",
    "Formulários de coleta de dados prontos em PDF",
    "Cronograma, orçamento e análise de riscos/benefícios elaborados",
    "Formulário de conflito de interesses preenchido",
    "Cadastro realizado na Plataforma Brasil",
    "CEP responsável identificado e confirmado com o orientador",
    "Submissão concluída e número do protocolo registrado",
    "Cronograma de relatórios de acompanhamento ao CEP definido"
  ],
  dica: "<p>Use o ChatGPT para <strong>simular as pendências mais comuns</strong> que os CEPs costumam solicitar e prepare respostas antecipadas.</p><p>Verifique o prazo médio de análise do CEP da sua instituição antes de definir o início da coleta no cronograma, alguns comitês levam 30 dias, outros mais de 60.</p><p>Após a aprovação, <strong>guarde o parecer consubstanciado em local seguro</strong>: você precisará dele para publicar o artigo e apresentar à banca. Aprofunde no capítulo correspondente do FiatLux: <a href='https://bit.ly/2024fiatlux' target='_blank' rel='noopener'>bit.ly/2024fiatlux</a>.</p>",
  cta: "<p>Com a aprovação do CEP em mãos, a jornada entra em uma nova fase: <strong>a execução</strong>. O planejamento está concluído, agora é hora de ir a campo.</p><p>No próximo módulo, você aprenderá como conduzir a coleta de dados de forma sistemática, ética e eficiente, mantendo o rigor do projeto aprovado em cada contato com os participantes. Você descobrirá onde os dados vivem e quais ferramentas de IA podem otimizar esse processo sem comprometer a qualidade da evidência. <strong>A pesquisa real começa aqui, avance com propósito!</strong></p>",
  fl: 10, flLabel: "Capítulo 10, Encaminhar o Projeto para o Comitê de Ética em Pesquisa",
  quiz: [
    { q: "Quando a coleta de dados pode começar?", opts: ["Assim que o projeto estiver escrito", "Após a aprovação formal do CEP, nunca antes", "Quando o orientador autorizar", "Após o cadastro na Plataforma Brasil"], a: 1, fb: "Nenhuma coleta pode ser iniciada antes da aprovação ética formal, é requisito da Resolução CNS 466/2012 e iniciar antes pode invalidar toda a pesquisa." },
    { q: "Por que o CEP também avalia os aspectos metodológicos do projeto?", opts: ["Para substituir o papel do orientador", "Porque uma pesquisa mal planejada também é eticamente inaceitável: desperdiça recursos e o tempo dos participantes", "Para escolher o método estatístico", "Por exigência das revistas científicas"], a: 1, fb: "Proteger o sujeito da pesquisa é também protegê-lo de ciência de má qualidade, método e ética são inseparáveis." },
    { q: "O que acontece após a aprovação do projeto pelo CEP?", opts: ["A responsabilidade ética termina", "É obrigatório enviar relatórios de acompanhamento a cada seis meses e um relatório final", "O TCLE pode ser dispensado", "O projeto pode ser alterado livremente"], a: 1, fb: "O compromisso ético dura enquanto a pesquisa durar, com relatórios semestrais e relatório final ao encerrar." },
    { q: "Qual sistema oficial é usado para submissão de pesquisas com seres humanos no Brasil?", opts: ["Plataforma Lattes", "SciELO", "Plataforma Brasil", "Portal de Periódicos CAPES"], a: 2, fb: "Toda a submissão ao CEP é feita eletronicamente pela Plataforma Brasil (plataformabrasil.saude.gov.br)." }
  ]
});
