LESSONS.push({
  id: "deixando-os-dados-falarem", fase: 2, num: 11,
  title: "Deixando os Dados Falarem: Análise Estatística",
  tagline: "Você organizou. Você tabulou. Agora é hora de perguntar: o que esses números realmente significam?",
  quote: { text: "Os dados não mentem, mas também não falam por si. É o rigor na análise estatística que transforma o silêncio em sentido e números em verdade.", author: "A Jornada do Pesquisador" },
  why: "<p>Você chegou ao momento mais esperado da jornada. Mas a análise estatística <strong>não é mágica</strong>: é um processo rigoroso que exige escolher o teste certo, aplicá-lo corretamente e interpretar seus resultados com honestidade. Neste módulo você vai entender a diferença entre estatística descritiva e inferencial, aprender quais ferramentas usar e — o mais importante — <strong>como não manipular os dados</strong> para chegar ao resultado que você gostaria.</p>",
  cenario: "<p>A planilha de Ana Vitória estava impecável: 60 participantes, 14 variáveis, sem células vazias. Ela abriu o JASP e ficou olhando para os botões. Qual teste usar? Voltou ao seu projeto de pesquisa e encontrou, no item de análise estatística: <em>“teste t de Student para amostras independentes para comparar as médias entre os grupos”</em>. Respirou fundo e seguiu o planejamento. O resultado: <strong>p = 0,032</strong>. Abaixo de 0,05 — diferença estatisticamente significativa. O coração acelerou, mas ela sabia que <strong>significância estatística não é o mesmo que importância clínica</strong>. Verificou o tamanho do efeito, olhou os intervalos de confiança e registrou tudo com transparência. Ciência de verdade.</p>",
  sections: [
    { icon: "🔍", title: "O que é analisar os dados?", html: "<p>Analisar os dados é o momento decisivo em que o pesquisador <strong>confronta a realidade dos resultados com as expectativas formuladas na hipótese</strong>. É um processo lógico e matemático que transforma dados brutos em evidências científicas confiáveis. Exige lógica, domínio técnico e honestidade intelectual. A análise divide-se em duas grandes etapas complementares:</p><ul><li><strong>Estatística descritiva:</strong> calcula medidas de posição (média, mediana, moda), medidas de dispersão (desvio padrão, amplitude interquartil) e medidas de forma (assimetria/skewness, achatamento/kurtosis). Organiza, resume e apresenta os dados com clareza;</li><li><strong>Estatística inferencial:</strong> aplica os testes estatísticos planejados (teste t, qui-quadrado, ANOVA, correlação de Pearson, regressões) para generalizar os resultados da amostra para a população-alvo, controlando o erro aleatório.</li></ul><p>💡 Ferramentas: <strong>JASP</strong> ou <strong>Jamovi</strong> (gratuitos, interface amigável); GraphPad QuickCalcs para testes rápidos online; ChatGPT/Gemini/Copilot/Claude para interpretar saídas dos softwares e esclarecer conceitos.</p>" },
    { icon: "⭐", title: "Por que isso é importante?", html: "<p>Sem análise estatística, todo o esforço anterior — planejamento, coleta, armazenamento e tabulação — <strong>perde seu valor científico</strong>. É a análise que permite distinguir um achado verdadeiro de um resultado aleatório. Ela:</p><ul><li>Determina a significância estatística dos resultados (p-valor, intervalos de confiança);</li><li>Revela a magnitude e a direção do efeito observado;</li><li>Permite a generalização dos resultados da amostra para a população-alvo;</li><li>Identifica a força da evidência e o grau de incerteza das conclusões;</li><li>Pode confirmar descobertas, refutar hipóteses ou levantar novas questões;</li><li>Fornece a base para as conclusões científicas e as recomendações práticas do estudo.</li></ul>" }
  ],
  steps: [
    "<strong>Abra o projeto de pesquisa</strong> e localize o item de análise estatística. Siga exatamente o que foi previsto, sem desvios ou improvisações.",
    "<strong>Execute a estatística descritiva primeiro:</strong> média, mediana, desvio padrão, frequências relativas e absolutas para todas as variáveis. Isso cria o retrato da sua amostra.",
    "<strong>Verifique os pressupostos do teste inferencial:</strong> normalidade dos dados (Shapiro-Wilk), homogeneidade de variâncias (Levene), tamanho amostral adequado. Se um pressuposto falhar, use o teste não paramétrico equivalente.",
    "<strong>Execute o teste inferencial planejado</strong> no software escolhido (JASP, Jamovi, SPSS, R). Registre o valor de p, o intervalo de confiança de 95% e o tamanho do efeito.",
    "<strong>Interprete com rigor:</strong> p < 0,05 indica significância estatística, mas não necessariamente importância clínica. Avalie também a magnitude do efeito (d de Cohen, por exemplo).",
    "<strong>Se realizar análises não previstas</strong>, identifique-as explicitamente no relatório final como análises a posteriori (não planejadas) e interprete-as com cautela — são exploratórias, não confirmatórias.",
    "<strong>Documente todo o processo:</strong> software usado, versão, testes aplicados e por quê. Essa transparência garante a reprodutibilidade da pesquisa."
  ],
  errors: [
    { e: "Realizar análises não previstas no projeto sem identificá-las como tal.", s: "Rotule-as como “análises a posteriori” no relatório — transparência não é falha de planejamento." },
    { e: "Confundir significância estatística com relevância clínica.", s: "Sempre calcule e reporte o tamanho do efeito. Um p = 0,001 com efeito minúsculo pode ser irrelevante na prática." },
    { e: "Escolher o teste estatístico após ver os dados (p-hacking).", s: "O teste deve estar definido no projeto antes da coleta. Mudar de teste para obter p < 0,05 é uma violação ética grave." },
    { e: "Delegar a análise inteiramente a um estatístico sem entender os resultados.", s: "Você precisa saber por que cada teste foi escolhido e o que significam os valores gerados. A responsabilidade pela análise é sempre do pesquisador." },
    { e: "Não verificar os pressupostos dos testes antes de aplicá-los.", s: "Antes do teste t, verifique normalidade; antes da ANOVA, homogeneidade. Ignorar pressupostos invalida os resultados." }
  ],
  licao: "<p>A análise dos dados é um <strong>instrumento de confirmação, não de convencimento</strong>. Ela existe para revelar o que os dados mostram, não o que você gostaria que mostrassem. O p-valor, os intervalos de confiança e os níveis de significância não são apenas números: são ferramentas que traduzem a força da evidência científica obtida. Conduza sua análise com seriedade, rigor e honestidade intelectual — e esteja preparado para defender cada número diante da banca.</p>",
  checklist: [
    "Análise estatística realizada exatamente conforme previsto no projeto",
    "Estatística descritiva concluída (média, mediana, DP, frequências) para todas as variáveis",
    "Pressupostos dos testes inferenciais verificados antes da aplicação",
    "Teste inferencial correto aplicado (conforme tipo de variável e desenho do estudo)",
    "p-valor, intervalo de confiança de 95% e tamanho do efeito registrados",
    "Análises não previstas identificadas como “a posteriori” no relatório",
    "Software utilizado, versão e testes aplicados documentados",
    "Resultados interpretados quanto à significância estatística e à relevância clínica",
    "Conclusões consistentes com os objetivos e a hipótese original do estudo"
  ],
  dica: "<p>Use o <strong>JASP</strong> ou o <strong>Jamovi</strong> — gratuitos, com interface visual e relatórios automáticos em APA. Ideais para iniciantes e estudos de pequeno a médio porte.</p><p>Para testes rápidos (qui-quadrado, teste t), experimente o <strong>GraphPad QuickCalcs</strong>, online e sem instalação.</p><p>O ChatGPT pode ajudar a interpretar a saída dos softwares: cole o resultado e pergunte “O que significam esse p-valor e esse intervalo de confiança?”.</p>",
  cta: "<p>Ana Vitória fechou o JASP com os resultados salvos. Ela tinha números, percentuais, um p-valor e o tamanho do efeito. <strong>Mas números sozinhos não contam uma história.</strong> Agora vem a parte que exige mais do pesquisador: transformar esses resultados em respostas. O que eles significam? Confirmam a hipótese? Contradizem a literatura? Que implicações têm para a prática clínica? No próximo módulo, você vai entender como transformar estatística em compreensão e números em conclusões científicas sólidas.</p>",
  fl: 14, flLabel: "Capítulo 14 — Analisar os Dados",
  quiz: [
    { q: "Qual é a diferença entre estatística descritiva e inferencial?", opts: ["A descritiva usa gráficos; a inferencial usa tabelas", "A descritiva organiza e resume os dados da amostra; a inferencial generaliza os resultados para a população-alvo com testes estatísticos", "São sinônimos", "A inferencial é opcional"], a: 1, fb: "Descritiva: medidas de posição, dispersão e forma. Inferencial: testes (t, qui-quadrado, ANOVA…) que generalizam da amostra para a população, controlando o erro aleatório." },
    { q: "O que é p-hacking?", opts: ["Usar software pirata para análise", "Escolher ou trocar o teste estatístico após ver os dados, buscando obter p < 0,05", "Calcular o p-valor manualmente", "Proteger os dados com senha"], a: 1, fb: "O teste deve estar definido no projeto antes da coleta. Mudar de teste para 'forçar' significância é uma violação ética grave." },
    { q: "Um resultado com p = 0,001 é automaticamente importante na prática clínica?", opts: ["Sim, quanto menor o p, maior a importância clínica", "Não: é preciso avaliar também o tamanho do efeito — um efeito minúsculo pode ser irrelevante na prática", "Sim, se a amostra for grande", "Não, pois p-valores não servem para nada"], a: 1, fb: "Significância estatística ≠ relevância clínica. Sempre calcule e reporte o tamanho do efeito junto com o p-valor e o intervalo de confiança." },
    { q: "O que fazer antes de aplicar um teste t de Student?", opts: ["Verificar os pressupostos, como a normalidade dos dados (ex.: Shapiro-Wilk)", "Remover os valores extremos", "Duplicar a amostra", "Arredondar os dados"], a: 0, fb: "Ignorar pressupostos invalida os resultados. Se um pressuposto falhar, usa-se o teste não paramétrico equivalente." }
  ]
});
